### ISSUE TITLE
Dynamic app load possible?

### ISSUE THREAD

**Issue by acalatrava** [Forairaaaaa/mooncake#9]
First of all, kudos on your projects. They are magnificent. I just bought a M5 Cardputer and I know you because of this. After browsing your projects I can tell without any doubt that you are a remarkable maker and developer.

I was browsing and getting to know your projects, and I was wondering if it would be possible to compile the apps as standalone binaries, linked to the main HAL->Mooncake and then stored the binaries along the icon on the SD card. Add some loading code to mooncake to push the apps into the launcher, and then, somehow, load the binary into memory and jump the execution to it.

What do you think? Will this be possible on the ESP32?

**Comment by Forairaaaaa** [comment]
Thanks~ I recently make [asset](https://github.com/Forairaaaaa/app_boilerplate/blob/main/app/app.cpp#L25) injectable dynamically as binary, it's the same idea to the serialization. But app is not just pure data, we might need to consider treating mooncake as a bootloader to jumps pc to the app binary, or write the app into flash on every opening like this [project](https://github.com/lovyan03/M5Stack_LovyanLauncher.git). Anyway, it's not easy on esp32~
